version: "3.8"

services:
  app:
    container_name: gain-mentoring-container
    image: gain-mentoring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - gain-db:/var/lib/mysql

volumes:
  gain-db: